services:
  db:
    image: postgres:15
    container_name: course_db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: CourseService
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d CourseService"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: course_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=CourseService;Username=dbuser;Password=dbpassword"
    ports:
      - "8080:80"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:
